resources:
  repositories:
  - repository: self
    type: git
    ref: teraform
jobs:
- job: Job_1
  displayName: Create Resource
  pool:
    name: Default
  steps:
  - checkout: self
    clean: true
  - task: TerraformCLI@0
    displayName: terraform init
    inputs:
      command: init
      workingDirectory: terraform
      environmentServiceName: e96a6e0d-672e-48cc-a750-83654b010b11
  - task: TerraformCLI@0
    displayName: terraform plan
    inputs:
      command: plan
      workingDirectory: terraform
      environmentServiceName: e96a6e0d-672e-48cc-a750-83654b010b11
...
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"
      
      AppService $(TF_OUT_NAME)
      echo $env
